language: go

go:
  - 1.3
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

services:
  - mysql

env: GO_ENV=test

before_install:
  - export PATH=/home/travis/gopath/bin:$PATH

install: make deps

before_script:
  - mysql -e "CREATE DATABASE majimoe_test;"
  - mysql -u root -e "GRANT ALL ON majimoe_test.* TO majimoe@localhost IDENTIFIED BY 'majimoe';"
  - goose -env test up

script:
  - godep go test