server:
  host: localhost
  port: 9000
  secret: dxxeQUOx5SPQMgdeoi8JTSKj1fRnFA6G
  logger: true

database:
  type: mysql
  path: "majimoe:majimoe@/majimoe_dev?parseTime=True"

mailgun:
  domain:
  private_key:
  public_key:

facebook:
  app_id: 822439461120188
  app_secret: 8e35ade4afc01c46fe0a0bb68a9dd16d

# For debugging
email_activation: false
