server:
  host: localhost
  port: 9000
  secret: dxxeQUOx5SPQMgdeoi8JTSKj1fRnFA6G

database:
  type: sqlite3
  path: /tmp/development.sqlite

reserved_domains:
  - www
  - email
  - api

mailgun:
  domain:
  private_key:
  public_key: