server:
  host: localhost
  port: 9000
  secret: dxxeQUOx5SPQMgdeoi8JTSKj1fRnFA6G
  logger: false

database:
  type: sqlite3
  path: ":memory:"

mailgun:
  domain:
  private_key:
  public_key:

facebook:
  app_id:
  app_secret:

# For debugging
email_activation: false
